### ISSUE TITLE
Possibility to adjust your container.

### ISSUE THREAD

**Issue by TheHanfried** [VatinMc/cursor-anchor#3]
I am sorry but i dont have an idea how to give a suggestion :-) 

I would love to be able to enable/disable each container.
Didnt find a config nor is it possible to view this setting in the mod menu.

I really love this mod and I dont see any other issue currently.

Thank you very much

**Comment by VatinMc** [comment]
Thanks for you suggestion! I also think it would be a nice feature.  
  
I need to research on how to implement Modmenu. I think it could take about a week, because I do not have much free time atm.  
  
I will answer here, when I have more information

**Comment by VatinMc** [comment]
I wanted to give you an update, so you know, I'm working on it :)  
![2024-12-21_17 59 17](https://github.com/user-attachments/assets/005122c8-6678-43f4-b69b-24bdb40df6de)
I think the Config-Screen looks ok-ish now. Also I implementend Modmenu, so you can access Config-Screen from Modmenu.  
  
Next step is to add functionality.

**Comment by TheHanfried** [comment]
I think this looks really good. I like how you also show the icons and not only the text :D 

Not sure what kind of functionality you could add. Do you have something in mind, that could work with your Cursor-Vision ?

**Comment by VatinMc** [comment]
Thank you :)  
The screenshot above shows a screen, which is only a display, you can't interact with it.  
Now I have implemented your features for version [1.21.1](https://modrinth.com/mod/cursor-anchor/version/1.2.0)  
  
Which version do you play on? So I can update this one next.

**Comment by TheHanfried** [comment]
alright I got it ^^ 

I am still on 1.21.1, because some addons I use are not out for 1.21.4 yet :-)

**Comment by VatinMc** [comment]
Perfect :)

**Comment by VatinMc** [comment]
Am I allowed to mention your Name on Modrinth in changelog?

**Comment by TheHanfried** [comment]
Sure, if you want to you can :)
